### ISSUE TITLE
Starting cjdroute in makeconfig

### ISSUE THREAD

**Issue by chpio** [thefinn93/cjdns-docker#1]
https://github.com/thefinn93/cjdns-docker/blob/master/makeconfig.sh#L28

Hi,
is this a bug?!

**Comment by thefinn93** [comment]
idk. This was really me just playing with docker. Where should that go?

**Comment by chpio** [comment]
[here](https://github.com/thefinn93/cjdns-docker/blob/master/startcjdns.sh#L6) or [here](https://github.com/thefinn93/cjdns-docker/blob/master/Dockerfile#L11)

And you should rewrite [this line](https://github.com/thefinn93/cjdns-docker/blob/master/Dockerfile#L10). The container will be started with the command: `${ENTRYPOINT} ${CMD}`([link to tah doc](http://docs.docker.io/reference/run/#cmd-default-command-or-options)). So the ENTRYPOINT arg is not necessary here use

```
RUN /tmp/makeconfig.sh
CMD startcjdns
```

to "makeconfig" it at build time (docker build .) or

```
CMD /tmp/makeconfig.sh && startcjdns
```

to "makeconfig" at run time (docker run ...).
Also "makeconfig.sh" is just a setup-script and should not start the container.

**Comment by thefinn93** [comment]
File a pull request if you want it fixed.
